-- Tabla de Roles
CREATE TABLE "role" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name TEXT NOT NULL,
  description TEXT
);

-- Tabla de Permisos
CREATE TABLE "permissions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_name VARCHAR(12) NOT NULL UNIQUE CHECK (permission_name IN ('Admin', 'Vet', 'User'))
);

-- Tabla de Usuarios
CREATE TABLE "user" (
  id BIGINT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  telephone_number TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  permissions BIGINT DEFAULT 3 REFERENCES permissions (id), -- Relación con la tabla permissions
  location TEXT,
  security_word TEXT,
   user_tokenvarchar,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Especies
CREATE TABLE specie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(100)
);

-- Tabla de Razas
CREATE TABLE breed (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  fk_specie BIGINT REFERENCES specie (id)
);

-- Tabla de Mascotas
CREATE TABLE pet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  fk_breed BIGINT REFERENCES breed (id),
  color TEXT,
  sex text,
  date_birth TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Dueños de Mascotas
CREATE TABLE pet_owners (
  id BIGINT PRIMARY KEY,
  user_id BIGINT REFERENCES "user" (id),
  pet_id BIGINT REFERENCES pet (id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Trabajadores
CREATE TABLE worker (
  id BIGINT PRIMARY KEY REFERENCES "user" (id),
  role_id BIGINT REFERENCES role (id),
  status TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_birth TIMESTAMP,
  location VARCHAR(50),
  gender VARCHAR(15),
  license_number VARCHAR(30),
  years_experience INT,
  education VARCHAR(200),
  certifications VARCHAR(200)
);

-- Tabla de Servicios
CREATE TABLE service (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT
);

-- Tabla de Horarios
CREATE TABLE schedule (
  id BIGINT PRIMARY KEY,
  date TIMESTAMP,
  monday VARCHAR(15),
  tuesday VARCHAR(15),
  wednesday VARCHAR(15),
  thursday VARCHAR(15),
  friday VARCHAR(15),
  worker_id BIGINT REFERENCES worker (id)
);

-- Tabla de Citas
CREATE TABLE appointment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT REFERENCES service (id),
  pet_owner_id BIGINT REFERENCES pet_owners (id),
  schedule_id BIGINT REFERENCES schedule (id),
  problem TEXT,
  date_request TIMESTAMP
);

-- Tabla de Categorías
CREATE TABLE category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  function TEXT
);

-- Tabla de Productos
CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  expiration_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description TEXT,
  price FLOAT,
  category_id BIGINT REFERENCES category (id)
);

-- Tabla de Inventario
CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES product (id),
  quantity INT NOT NULL,
  status TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Productos de Tratamiento
CREATE TABLE treatment_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES product (id),
  quantity INT NOT NULL
);

-- Tabla de Tratamientos
CREATE TABLE treatment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  details TEXT,
  remarks TEXT,
  product_id BIGINT REFERENCES treatment_product (id),
  price FLOAT
);

-- Tabla de Consultas
CREATE TABLE consultation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT REFERENCES appointment (id),
  diagnosis TEXT,
  medical_exams TEXT,
  remarks TEXT,
  treatment_id BIGINT REFERENCES treatment (id),
  price FLOAT,
  utensils TEXT
);

-- Tabla de Historial Médico
CREATE TABLE medical_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id BIGINT REFERENCES pet (id),
  consultation_id BIGINT REFERENCES consultation (id)
);

-- Tabla de Detalles de Factura
CREATE TABLE detail_invoice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_id BIGINT REFERENCES consultation (id),
  treatment_id BIGINT REFERENCES treatment (id),
  total_amount FLOAT,
  appointment_id BIGINT REFERENCES appointment (id)
);

INSERT INTO permissions (permission_name)
VALUES 
  ('Admin'),
  ('Vet'),
  ('User');

 INSERT INTO "role" (role_name, description)
VALUES 
  ('Veterinario', 'Responsable de diagnosticar y tratar a los animales.'),
  ('Técnico Veterinario', 'Asiste al veterinario en los procedimientos y el cuidado de los pacientes.'),
  ('Recepcionista', 'Gestiona las citas, recibe a los clientes y maneja las tareas administrativas.'),
  ('Asistente de Canil', 'Cuida de los animales que se quedan en el canil.'),
  ('Peluquero', 'Proporciona servicios de peluquería a las mascotas.');
  
  INSERT INTO specie (name, description)
VALUES 
  ('Perro', 'Especie canina doméstica.'),
  ('Gato', 'Especie felina doméstica.'),
  ('Ave', 'Especie de aves domésticas.');

  INSERT INTO breed (name, description, fk_specie)
VALUES 
  ('Labrador Retriever', 'Raza de perro amigable y enérgica.', 1), -- Perro
  ('Bulldog Francés', 'Raza de perro pequeña y de compañía.', 1), -- Perro
  ('Pastor Alemán', 'Raza de perro conocida por su inteligencia y habilidades de trabajo.', 1), -- Perro

  ('Siames', 'Raza de gato conocida por sus ojos azules y su pelaje corto.', 2), -- Gato
  ('Persa', 'Raza de gato con pelaje largo y rostro aplanado.', 2), -- Gato
  ('Maine Coon', 'Raza de gato grande y de pelaje denso.', 2), -- Gato

  ('Canario', 'Raza de ave conocida por su canto.', 3), -- Ave
  ('Periquito', 'Raza de ave pequeña y colorida.', 3), -- Ave
  ('Cacatúa', 'Raza de ave exótica y social.', 3); -- Ave

-- Insertar un administrador en la tabla "user"
INSERT INTO "user" (id, first_name, last_name, email, password, permissions)
VALUES 
  (1, 'Admin', 'User', 'admin@example.com', 'securepassword', 1); -- Administrador

-- Insertar dos usuarios normales en la tabla "user"
INSERT INTO "user" (id, first_name, last_name, email, password, permissions)
VALUES 

  (2, 'John', 'Doe', 'john.doe@example.com', 'securepassword', 3),
  (3, 'Jane', 'Smith', 'jane.smith@example.com', 'securepassword', 3);

 -- Insensertar un trabajador
 INSERT INTO "user" (id, first_name, last_name, telephone_number, email, password, permissions, location) VALUES
(4, 'Carlos', 'Rodríguez', '4567890123', 'carlos@example.com', 'hashedpassword4', 2, 'Ciudad Principal');

  INSERT INTO worker (id, role_id, status, date_birth, location, gender, license_number, years_experience, education, certifications) VALUES
(4, 1, 'Activo', '1985-05-15', 'Ciudad Principal', 'Masculino', 'VET12345', 10, 'Doctorado en Medicina Veterinaria', 'Certificación en cirugía animal');

--Insertar mascosatas	
INSERT INTO pet (name, fk_breed, color, sex, date_birth) VALUES
('Max', 1, 'Dorado', 'Macho', '2020-03-10'),
('Luna', 2, 'Blanco y negro', 'Hembra', '2021-07-22');

INSERT INTO pet_owners (id, user_id, pet_id) VALUES
(3, 2, 3),
(4, 3, 4);

INSERT INTO schedule (id, date, monday, tuesday, wednesday, thursday, friday, worker_id) VALUES
(1, '2023-05-22', '09:00-17:00', '09:00-17:00', '09:00-17:00', '09:00-17:00', '09:00-17:00', 4);

INSERT INTO service (name, description)
	VALUES 
  ('Consulta General', 'Evaluación médica general de la mascota.'),
  ('Vacunación', 'Aplicación de vacunas preventivas para diversas enfermedades.'),
  ('Desparasitación', 'Tratamiento para eliminar parásitos internos y externos.'),
  ('Cirugía', 'Procedimientos quirúrgicos para diversas condiciones médicas.');



INSERT INTO appointment (service_id, pet_owner_id, schedule_id, problem, date_request) VALUES
(1, 3, 1, 'Revisión anual', '2023-05-23 10:00:00'),
(2, 4, 2, 'Vacunación programada', '2023-05-24 14:30:00');




  -- Insertar categorías de productos
INSERT INTO category (name, function)
VALUES 
  ('Alimento', 'Productos alimenticios para mascotas'),
  ('Medicina', 'Medicamentos para tratamientos y prevención'),
  ('Juguetes', 'Juguetes para el entretenimiento de las mascotas'),
  ('Accesorios', 'Accesorios varios para mascotas');

-- Insertar productos
INSERT INTO product (name, expiration_date, description, price, category_id)
VALUES
  ('Croquetas para perro', '2025-12-31', 'Alimento balanceado para perros adultos', 29.99, 1),
  ('Antipulgas', '2024-08-15', 'Tratamiento para eliminar pulgas y garrapatas', 19.99, 2),
  ('Pelota de goma', NULL, 'Juguete de goma para perros', 5.99, 3),
  ('Correa de nylon', NULL, 'Correa ajustable para pasear perros', 12.99, 4);

-- Insertar inventario
INSERT INTO inventory (product_id, quantity, status)
VALUES
  (1, 100, 'Disponible'),
  (2, 50, 'Disponible'),
  (3, 200, 'Disponible'),
  (4, 75, 'Disponible');

-- Insertar productos de tratamiento
INSERT INTO treatment_product (product_id, quantity)
VALUES
  (2, 1), -- Antipulgas
  (2, 2); -- Antipulgas

-- Insertar tratamientos
INSERT INTO treatment (name, details, remarks, product_id, price)
VALUES
  ('Desparasitación externa', 'Aplicación de antipulgas para eliminar parásitos externos', 'Aplicar cada 3 meses', 1, 25.00);

-- Insertar consultas
INSERT INTO consultation (appointment_id, diagnosis, medical_exams, remarks, treatment_id, price, utensils)
VALUES
  (1, 'Consulta de rutina', 'Análisis de sangre', 'Mascota en buen estado de salud', 1, 50.00, 'Estetoscopio, termómetro');

-- Insertar historial médico
INSERT INTO medical_history (pet_id, consultation_id)
VALUES
  (11, 1);

-- Insertar detalles de factura
INSERT INTO detail_invoice (consultation_id, treatment_id, total_amount, appointment_id)
VALUES
  (1, 1, 75.00, 1);




  select * from "user";

  select * from "worker";

  select * from "pet";
  
  select * from "pet_owners";

  select * from "appointment";

  select * from "consultation";

  select * from "medical_history";

  ALTER TABLE "user" ADD COLUMN security_word TEXT;

  ALTER TABLE "user" ADD COLUMN user_token varchar;
